### PR TITLE
Altairz80: M68K: Update Musashi core to latest version

### PR DESCRIPTION
**Pull request by hharte**
The 3.3 version  of the Musashi core in AltairZ80 was under a bespoke license.  Update to the latest from https://github.com/kstenerud/Musashi which is licensed under an MIT license.

FYI, @psco

### CODE REVIEW

**Comment by markpizz** [comment]
Historically, all PRs for the AltairZ80 simulator get approved by @psco before merge...

Meanwhile, you've got two PR's that have pending merges while they both have the same parent.  I usually asked one to wait until the other is merged.  Since you're one of the PR authors, you can do that yourself to avoid merge commits which hopefully would now be rejected anyway due to properties of the master branch...

**Comment by hharte** [comment]
Thanks @markpizz for the feedback.  I gave @psco a heads-up that this change was coming.  I’m fine to rebase this PR on top of the libedit PR after it’s merged, if that one goes first.  I don’t care for merge commits either.

**Comment by markpizz** [comment]
@pkoning2 is doing the merging so it should be trivial for him to do.

**Comment by psco** [comment]
I would appreciate if @pkoning2 would hold back the merge as I have a couple of open questions for Howard.

**Comment by pkoning2** [comment]
Thanks for the note, will do.  Please follow up with an "all clear" when ready.

**Comment by hharte** [comment]
Thanks @psco for fixing the "expect" hang with the M68K CPU.

-Howard

**Comment by psco** [comment]
Thanks @hharte! This is fine and should be merged.

**Comment by hharte** [comment]
@pkoning2 this is ready to go.

**Pull request merged**
