### PR TITLE
3B2-700 Initial Public Release

### PR DESCRIPTION
**Pull request by sethm**
This commit introduces dozens of changes to make the 3B2-700 simulator fully functional and ready for wider use. In addition to 3B2-700 availability, this commit includes a tremendous amount of refactoring of the 3B2-400 and common code to make the project structure easier to maintain and reason about.

One final important change: ROM files are no longer included in the source code. 3B2 ROM images must be obtained separately and loaded into the simulator before boot.

Changes:

- The 3b2 target has been aliased to 3b2-400
- The formerly named 3b2-600 project has become 3b2-700
- SCSI QIC tape support has been added to sim_scsi.c
- Header files have been reworked to reduce complexity of includes
- Common code has been consolidated
- Timer code has been unified

**Notes to reviewers:**

1. I am cautious about the changes I've made to sim_scsi.c. I do not believe I have changed or modified any existing behavior, but I would really appreciate a second set of eyes on these changes! The goal was to introduce a unit flag that could mark a tape device as being QIC. SCSI QIC tapes operate only in fixed-block mode, and behave slightly differently than other streaming SCSI tapes with regard to the 6-byte READ command: the command requests a number of blocks to read, each assumed to be a fixed 512-byte length.
2. The Windows projects have been updated, but, critically, I **do not have a Windows box to test these on right now**. I'm working on getting a Windows development environment up and running again, but it may be a little while. If someone could test building this on Windows before approving the pull, I would be very grateful.

### CODE REVIEW

**Comment by pkoning2** [comment]
The sim_scsi changes look reasonable.  I haven't used sim_scsi though; I'm looking at this from general SCSI background.

Does any of this need updates to anything in the "doc" directory?  Perhaps not, there isn't a 3b2_doc.doc file.

**Comment by sethm** [comment]
> Does any of this need updates to anything in the "doc" directory? Perhaps not, there isn't a 3b2_doc.doc file.

No doc updates, no. I have meant to write a proper doc for the 3B2 simulators, but I haven't gotten around to it yet.

**Comment by pkoning2** [comment]
Let's give this a day or two for others to look at this; if there isn't any concern raised it can then be merged.

**Comment by sethm** [comment]
I just updated with a force-push, because I was able to get a Windows environment set up (finally!) and it revealed two compile warnings that I wanted to take care of. The warnings were related to unused code in 3B2/3b2_ni.c. Those warnings are now dealt with, and things seem to build OK on Windows.

I'll leave the PR open for a day or two to gather up additional comments and then we can merge if there are no other changes needed.

**Comment by sethm** [comment]
Last call! If there are no other reviews or objections, I will merge this change in a few hours.

**Comment by markpizz** [comment]
It looked good to me.

How/why did the ROM images go away?

**Comment by sethm** [comment]
> It looked good to me.
> 
> How/why did the ROM images go away?

I pulled them out of an abundance of caution with regard to intellectual property rights. I never got permission to distribute them, and it's not even clear who the current rights owners are. I feel a little safer decoupling them and hosting them elsewhere so that if a request ever does come in to pull them down, it wouldn't affect SIMH directly.

ROMs can be loaded with a "LOAD -B <file>" command, but this is a breaking change. I'm updating the webpage documentation right now to go live at the same time I merge this PR.

**Comment by sethm** [comment]
Sigh -- I wasn't aware that merging the PR through GitHub would lead to an unclean history in the tree. I don't like that. If that is something that's fixable at this point, I would like to fix it. If not, it's a lesson learned for next time.

**Comment by markpizz** [comment]
So, you're going to distribute the same contents via sa different mechanism.

This falls in the same domain as essentially all the other ROM stuff and would probably be a concern for a simh "package" that includes all the simulators at least in Linux distros.  I've suggested that the "right" simh package should merely be an installer which describes what simh is and then allows the user running the installer to select the simulator(s) they are interested in at that installer then downloads the pre-built binaries for the appropriate platform.

**Comment by markpizz** [comment]
> Sigh -- I wasn't aware that merging the PR through GitHub would lead to an unclean history in the tree. I don't like that. If that is something that's fixable at this point, I would like to fix it. If not, it's a lesson learned for next time.

Back at the end of  July I made this observation and suggestion to Paul, and received no comment back, but it is specifically relevant to the problem you just encountered:

It seems that sometime in recent weeks or over the last few months, Github finally has added the concept of policy protection rules for repo branches.  In particular, the policies that I manually followed for the master branch are now available:  “Require linear history” (thus avoiding merge commits), “Include administrators”, DO NOT “Allow force pushes”, DO NOT “Allow deletions”.  These settings belong on the public master branch.  The force push and deletions strategy are appropriate to avoid changing history.  History changes on personal repos and/or branches in personal repos is appropriate since such branches are only transit points for migration into the public repo’s branch(s).  I’d suggest these protections on the master and Supnik-Current branches.

**Comment by pkoning2** [comment]
Re merging: for some reason Github uses a mode that always does an explicit merge commit even when it doesn't need to.  The way I merge things is to check out master, then merge the PR branch with an explicit `--ff-only` switch.
It may be Github can be made to do things in a linear way by telling it to do merging via rebase, I have not investigated that.

**Comment by pkoning2** [comment]
I made those changes, please report any problems seen.  "Linear history" is now enabled for master and Supnik branches.

**Pull request merged**
