### PR TITLE
Add MMS-1 support.

### PR DESCRIPTION
**Pull request by ragge0**
Write MMS-1 support (Memory Management 1).    Also a lot of other bugfixes.
Can now boot the last test programs from floppy, and runs INSTRUCTION-C and PAGING-C without errors.

### CODE REVIEW

**Comment by markpizz** [comment]
Please follow the project convention relating to the format of commit messages.  Specifically., the current commit messages is merely:
```
More saker.
```
The project convention is:
```
affected-component-or-simulator: <Summary-description-of-change-less-than-80>
<blank-line-if-additional-commit-comments>
<additional-commit-comments-with-lines-wrapped-less-than-80>
```

The additional comments should describe the thinking and accomplishment.

Elaborate comments in the PR description or comments are less desirable since these are merely information hanging on the github repo.  Commit comments move along with all copies/clones of the repo.

**Comment by ragge0** [comment]
Gee, I thought I fixed this :-/

Can you please send me the command to update this?  I am getting lost.
I seem to spend more time getting git to behave than the actual 
implementation of the simulator...

-- Ragge

Den 2023-05-14 kl. 22:21, skrev Mark Pizzolato:

**Comment by markpizz** [comment]
I've always used a GUI to do various basic git operations only entering command line stuff for complex activities.  

Presuming you don't have that option, I just tried the following:

```
$ # unwind the most recent commit in the current branch 
$ # leaving the changes staged
$ git reset --soft HEAD^
$ # commit again (on my system git invokes an editor to enter the commit message)
$ git commit
$ # I composed the commit message and saved the result with that message
$ # Update the existing PR replacing the prior commit with the current state
$ git push --force
```

**Comment by pkoning2** [comment]
Changing the comments on your last commit is trivial -- "git commit --amend" will do that.  Then "git push --force" will send the amended commit to the server.  No need for backing out the commit or that sort of thing.

Similarly you can use --amend to make other changes, for example add a file to the commit that was missed, or change the author, or remove a file from the commit that wasn't supposed to be part of it.

Things get a whole log uglier if you need to "change history" further back.  In that case, you do have to reset back to the last good point and redo what you needed.  But the special case of only the last commit is easy and handled well by git.

**Comment by ragge0** [comment]
Thanks, I tried so earlier and I think it worked:-)

So, then everything should be OK I assume?

-- R

Den 2023-05-15 kl. 20:11, skrev Paul Koning:

**Comment by markpizz** [comment]
Well, I now see a different commit message.  You've got success there.

HOWEVER, will you please follow the suggested project commit message format.  If it is not clear, discuss here before changing it again!

**Comment by ragge0** [comment]
Ok, what is the problem with it?  As fas as I understood it follows your 
guidelines?  Here is from the commit log.

commit 3a3d7dd1908e8456487957a126a5877b3ade6bfa (HEAD -> master, 
origin/master, origin/HEAD)
Author: Anders Magnusson ***@***.***>
Date:   Sun May 14 21:46:21 2023 +0200

     MMS-1 support (Memory Management 1) + other fixes for Nord-100.

     Can now boot the last test programs from floppy, and runs INSTRUCTION-C
     and PAGING-C without errors.


-- Ragge

Den 2023-05-15 kl. 20:30, skrev Mark Pizzolato:

**Comment by markpizz** [comment]
Given this:
```
affected-component-or-simulator: <Summary-description-of-change-less-than-80>
<blank-line-if-additional-commit-comments>
<additional-commit-comments-with-lines-wrapped-less-than-80>
```
This commit should at least start with:
```
ND100:
```

**Comment by ragge0** [comment]
Ok, I have tried again :-)

-- R

Den 2023-05-15 kl. 20:37, skrev Mark Pizzolato:

**Comment by markpizz** [comment]
Looks good to merge.

**Pull request merged**
