### PR TITLE
RK source consistency

### PR DESCRIPTION
**Pull request by al20878**
Please consider the following fix for source code typos

### CODE REVIEW

**Comment by pkoning2** [comment]
I noticed another typo: in the help text, 128 words/sector (correct) and 256 words/drive (should be "sector").

**Comment by markpizz** [comment]
> I noticed another typo: in the help text, 128 words/sector (correct) and 256 words/drive (should be "sector").

Good catch.

Meanwhile, once again, the commit comment should follow the project standard.  I suggest:

PDP11: Correct wording for RK MTAB entries and help text

**Comment by al20878** [comment]
I updated the commit message, and also included the fix for words/sector that Paul found.
(The cyl count is a copy-n-paste blunder from the RL code.)

**Comment by pkoning2** [comment]
I was wondering about that 2* thing.

**Pull request merged**
