### PR TITLE
AltairZ80: Changes to support SCP MS-DOS and CompuPro CP/M-68K

### PR DESCRIPTION
**Pull request by hharte**
With these changes, [MS-DOS 2.11](https://github.com/hharte/MS-DOS) and most of the SCP disk images (except those for the North Star disk controller) on [bitsavers.org](http://bitsavers.org/bits/SeattleComputerProducts/) can run.

Additionally, by adding memory-mapped I/O to the M68K simulation, [CompuPro CP/M-68K v1.1I](http://bitsavers.org/bits/Compupro/CompuPro_68K_System_Masters.zip) can also run.

FYI, @psco , as discussed and reviewed offline.

### CODE REVIEW

**Comment by hharte** [comment]
@pkoning2 if you take @deltecent ’s AltairZ80 PR #118 and PR #121 changes first, I’ll be happy to rebase these on top, resolve conflicts and re-test.

**Comment by pkoning2** [comment]
@hharte all set.

**Comment by hharte** [comment]
Compiled with:
VS 2022 (Debug and Release)
VS 2008 (Debug and Release)
MacOS (x64) clang-1400.0.29.202 
Linux gcc 10.2.1

SIMH running on Windows, Linux, MacOS:
CompuPro CP/M-80
CompuPro CP/M-86
SCP 86-DOS
MS-DOS 2.11
CompuPro CP/M-68K v1.3 (68000 and 68010 versions)
CP/M-68K v1.2
CP/M-80 (Altair) ZEXALL Z80 instruction set test.

FYI, @psco , @pkoning2

**Comment by psco** [comment]
@hharte Thank you Howard, this looks good! @pkoning2 This can be merged, thanks

**Comment by hharte** [comment]
Here are packages that can be used with these changes:
MS-DOS 2.11: https://github.com/hharte/altairz80-packages/tree/main/msdos211_test

CompuPro CP/M-68K v1.3:
https://github.com/hharte/altairz80-packages/tree/main/ccpm68k13

**Pull request merged**
