### PR TITLE
PDP11: RF11: Fix DAE computation in service routine

### PR DESCRIPTION
**Pull request by al20878**
This is a re-do of RP #241 as confirmed by Bob Supnik (and without the "window dressing")
Please apply

### CODE REVIEW

**Comment by al20878** [comment]
Can this please be pushed?  Bob Supnik told me he had applied this patch to his V3 code (back on Jun 26, in a private email)

**Comment by al20878** [comment]
May I ask what is preventing this patch to get merged? (and #302 and #304, for that matter?)

**Comment by pkoning2** [comment]
Merged.

**Comment by al20878** [comment]
@pkoning2 :

Thanks, but something is not going right with all these merges...  This is what I see:

ClosedWithUnmergedCommits

"Closed with unmerged commits" and also the icon is a broken merge.

There's still #304 pending with an obvious fix.  Could you please push it as well?

**Comment by pkoning2** [comment]
You're looking at a github bug.  Rather than merge the changes one at a time (which triggers a build each time) I rebase and merge them in a local workspace and then push them all.  Github can't understand that process, and this is what you see as a result.  Look in the resulting code, you should find the correct content.

**Pull request closed without merging**
