### PR TITLE
KA10: Added support for Address Stop (lars)

### PR DESCRIPTION
**Pull request by rcornwell**
Address Stop register and functions from Lars.

### CODE REVIEW

**Comment by markpizz** [comment]
The dates at the top of the 3 revised documents are in the future.  Are you in some sort of time warp?  :-)

**Comment by rcornwell** [comment]
Yes, I must be.

**Comment by rcornwell** [comment]
Dates should be today.

**Comment by rcornwell** [comment]
Do I need to rebase this commit, or can it be pulled in?

**Comment by markpizz** [comment]
To avoid useless merge commits, someone has to rebase.  Either you, or someone doing the merge...

**Comment by rcornwell** [comment]
Rebased

**Comment by markpizz** [comment]
This PR looks ready for merge.  Letting PRs sit for too long ends up forcing folks who come along with the next (and additional) PR to have to rebase to avoid merge commits.

**Pull request merged**
