### PR TITLE
VAX: VAXstation 100 interface device

### PR DESCRIPTION
**Pull request by larsbrinkhoff**
I will implement this and make it talk to my [VAXstation 100 emulator](https://github.com/larsbrinkhoff/absolutely-not-a-vaxstation100-emulator/tree/stuff).

### CODE REVIEW

**Comment by larsbrinkhoff** [comment]
I have been using this device with 4.3BSD for a while, and it seems stable.  I'm posting a draft pull request for comments.

I would have called it VS, but that name is already take.  I opted for UW - unibus window - instead.  I gather there's also some other board called unibus window, but it's for multiprocessor systems so maybe it's a long shot for SIMH to support that.

**Comment by markpizz** [comment]
This is an addition the VAX780 simulator, so the commit message should start with VAX780:...

**Comment by larsbrinkhoff** [comment]
It will also be added to VAX730 and VAX750, at the least.  Any Unibus VAX, really.  In theory any Unibus machine, but I don't suppose PDP-11 or KS10 would be very useful.

**Comment by markpizz** [comment]
> It will also be added to VAX730 and VAX750, at the least. Any Unibus VAX, really

I have usually had commits affecting this as:

Unibus VAXen: M7452 Unibus window module for station 100

**Comment by larsbrinkhoff** [comment]
Please review.

**Comment by markpizz** [comment]
1 - There is a typo in the change to "Visual Studio Projects\VAX750.vcproj".  You duplicated the vax_syscm.c lines and forgot to change the second instance to vax_uw.c.
2 - The device DIB is setup as if it were to get Address and Vector via autoconfigure, but no such details is properly configured in pdp11_io_lib.c.  It seems that there is a place for this that mentions VS100.
3 - Since this device generates interrupts, there should be at least a MTAB entry to display the configured Vector.

What software drives this device under what OS?

**Comment by pkoning2** [comment]
I thought VMS supported that.  Or am I confused with Vaxstation 1?

**Comment by markpizz** [comment]
The VAXStation I was a MicroVAX I (Qbus system) with a QVSS (VCB01) installed that interfaced to a Video Display, a keyboard and mouse.

That system could do the DEC specific graphics and possibly X Windows when DEC added DECwindows.

I honestly never saw a VAXStation 100.  What part did the VAX play in this system?  If it was just a Unibus graphics interface, akin to the QVSS (VCB01), then I don't understand why Lars' implementation seems to be setup to communicate with something external via TCP/IP???  Additionally confusing is the fact that it doesn't actually have any graphics capabilities (keyboard or mouse either)???

**Comment by ethandicks** [comment]
On Tue, May 2, 2023 at 3:53 PM Mark Pizzolato ***@***.***> wrote:
> I honestly never saw a VAXStation 100. What part did the VAX play in this system? If it was just a Unibus graphics interface, akin to the QVSS (VCB01), then I don't understand why Lars' implementation seems to be setup to communicate with something external via TCP/IP??? Additionally confusing is the fact that it doesn't actually have any graphics capabilities (keyboard or mouse either)???

The VS100 was a 68000-based box that rendered graphics, drove a CRT,
and had mouse/keyboard/tablet connections that attached back to a host
Unibus machine with a fiber connection.  The Unibus board essentially
just mapped a chunk of Unibus to the VS100 and pushed the bits back
and forth transparently.

Functionally, from a software standpoint it would be like having a
custom 68000-based workstation peripheral interface stuck right into
your 11/7xx machine, but the fiber connection lets you put the tube
and the mouse and the keyboard outside of your machine room.

-ethan

**Comment by markpizz** [comment]
Thanks for the explanation.  

So, where is the simulator which implements the graphics side of this?

**Comment by larsbrinkhoff** [comment]
My VAXstation 100 emulator is here: https://github.com/larsbrinkhoff/absolutely-not-a-vaxstation100-emulator/tree/stuff

On the host side, I'm testing this with 4.3BSD and X10.  For VMS, there is this: http://www.9track.net/bits/dec/vs100/

**Comment by larsbrinkhoff** [comment]
The interrupt vector is programmed in software by writing CSR7.

**Comment by larsbrinkhoff** [comment]
The VS100 is of some historical note since the X Window System was first written for this device.  X was first used internally by the CLU group at MIT, but was quickly adopted by Project Athena.  After a while, DEC ported X - then at release 6 - to the MicroVAX.  X10 still supports the VS100 (but X11 does not).  Jim Gettys has expressed interest in getting older X versions running using my emulator.  He said he will search his archives for older releases.

**Comment by markpizz** [comment]
> > 3 - Since this device generates interrupts, there should be at least a MTAB entry to display the configured Vector.
> The interrupt vector is programmed in software by writing CSR7.

I didn't say anything about setting the vector with a MTAB entry.  If the vector is configured by software, that's nice.  There certainly are other devices which do this (XQ, RQ, TQ and others).  You should still provide a display of what the vector has been set to.

> 2 - The device DIB is setup as if it were to get Address and Vector via autoconfigure, but no such details is properly configured in pdp11_io_lib.c. It seems that there is a place for this that mentions VS100.

You didn't address this point.

The line in pdp11_io_lib.c that currently says:
```
    { { NULL },          1,  1, 16, 4 },                /* VS100 */
```
should say:
```
    { { "UW" },          1,  1, 16, 4 },                /* VS100 */
```

**Comment by markpizz** [comment]
> The VS100 is of some historical note since the X Window System was first written for this device. X was first used internally by the CLU group at MIT, but was quickly adopted by Project Athena. After a while, DEC ported X - then at release 6 - to the MicroVAX. X10 still supports the VS100 (but X11 does not). Jim Gettys has expressed interest in getting older X versions running using my emulator. He said he will search his archives for older releases.

Interesting.  I did various things for the X terminal company (NCD - Network Computing Devices) from their earliest days.  I was responsible for the engineering development side of all their VMS related support for use of their devices connected to VMS including the X over serial lines called X-remote, so I had direct involvement with the X world.  I remember discussions at NCD when they migrated from X10 to X11.

**Comment by markpizz** [comment]
> My VAXstation 100 emulator is here: https://github.com/larsbrinkhoff/absolutely-not-a-vaxstation100-emulator/tree/stuff

Since you've developed several simh simulators, why wasn't the VAXstation 100 one of them?

This PR should have some specific related documentation (beyond this discussion) that ties the UW device to your simulator.

**Comment by markpizz** [comment]
> The line in pdp11_io_lib.c that currently says:
>
>     { { NULL },          1,  1, 16, 4 },                /* VS100 */
>
> should say:
>
>    { { "UW" },          1,  1, 16, 4 },                /* VS100 */
>

AND

vax_uw.c line 148 should say:
```
    &uw_dib, DEV_UBUS | DEV_DISABLE | DEV_DIS | DEV_DEBUG, 0,
```
instead of:
```
    &uw_dib, DEV_DISABLE | DEV_DIS | DEV_DEBUG, 0,
```
and line 391 should say:
```
return auto_config (dptr->name, (dptr->flags & DEV_DIS)? 0 : 1);    /* auto config */
```
instead of:
```
return SCPE_OK;
```

**Comment by markpizz** [comment]
In the MTAB array in vax_uw.c
add this line:
```
    { MTAB_XTD|MTAB_VDV, 0, "VECTOR", NULL,
      NULL, &show_vec, NULL, "Interrupt vector" },
```

**Comment by larsbrinkhoff** [comment]
Thanks, I added the changes you provided.

**Pull request merged**
