### PR TITLE
Year end update to simulators.

### PR DESCRIPTION
**Pull request by rcornwell**
General updates to my simulators. These patches should not be flattened as they refer to multiple simulators.

### CODE REVIEW

**Comment by markpizz** [comment]
More warnings...

```
1>i7090_cpu.c
1>..\I7000\i7090_cpu.c(3415) : error C2220: warning treated as error - no 'object' file generated
1>..\I7000\i7090_cpu.c(3415) : warning C4244: 'function' : conversion from 't_uint64' to 'int', possible loss of data

1>i7080_cpu.c
1>..\I7000\i7080_cpu.c(2571) : error C2220: warning treated as error - no 'object' file generated
1>..\I7000\i7080_cpu.c(2571) : warning C4101: 'ta' : unreferenced local variable
1>..\I7000\i7080_cpu.c(2570) : warning C4101: 'j' : unreferenced local variable
1>..\I7000\i7080_cpu.c(2629) : warning C4101: 'ta' : unreferenced local variable
1>..\I7000\i7080_cpu.c(2628) : warning C4101: 'j' : unreferenced local variable
```

**Comment by markpizz** [comment]
Looks OK now.  Are you going to squash those extra repair commits?

**Comment by rcornwell** [comment]
I can backup and repush the I7000 patches.

**Comment by markpizz** [comment]
Does this fix #325?

**Comment by rcornwell** [comment]
Yes

**Comment by pkoning2** [comment]
I wonder why the "rebase and merge" button shows up red and not active.

**Comment by rcornwell** [comment]
Do you need me to recreate this PR?

**Comment by pkoning2** [comment]
Probably not, if we can figure out how to rerun the failed test.

**Comment by markpizz** [comment]
The failed test had nothing to do with these simulators.

This PR is good to merge.

**Comment by pkoning2** [comment]
Thanks, I thought that was the case.  Do you know how to get the "Rebase and merge" button to come to life?

**Comment by markpizz** [comment]
> Do you know how to get the "Rebase and merge" button to come to life?

I never used that functionality in the web interface since i always merged and tested locally before pushing the results directly.

**Comment by pkoning2** [comment]
Ok, so I did it that way.  The disadvantage is that GitHub doesn't recognize it as a merge since it's a rebase, so I have to close this PR manually and its status is confusing (it should be "merged").

Merged.

**Pull request closed without merging**
