### PR TITLE
Compile fix: replaced Uint8 by uint8.

### PR DESCRIPTION
**Pull request by folkertvanheusden**
Compilation fix for at least Ubuntu 24.04

### CODE REVIEW

**Comment by markpizz** [comment]
I just installed a new Ubuntu 24.04 VM, and built the code here in the open-simh/simh master branch and it compiles various simulators which include the file you are suggesting needs a change and there are absolutely no compilation errors.

More evidence of a problem would be useful.
```
mark@Ubuntu-24-04x64:~$ git clone https://github.com/open-simh/simh open-simh
Cloning into 'open-simh'...
remote: Enumerating objects: 36644, done.
remote: Counting objects: 100% (36643/36643), done.
remote: Compressing objects: 100% (7979/7979), done.
remote: Total 36644 (delta 28729), reused 36113 (delta 28581), pack-reused 1
Receiving objects: 100% (36644/36644), 70.52 MiB | 16.83 MiB/s, done.
Resolving deltas: 100% (28729/28729), done.
mark@Ubuntu-24-04x64:~$ cd open-simh/
mark@Ubuntu-24-04x64:~/open-simh$ make pdp11
lib paths are: /lib/x86_64-linux-gnu/ /lib/ /usr/lib/
include paths are:  /usr/lib/gcc/x86_64-linux-gnu/13/include /usr/local/include /usr/include/x86_64-linux-gnu /usr/include
using libm: /lib/x86_64-linux-gnu/libm.so
using librt: /lib/x86_64-linux-gnu/librt.a
using libpthread: /lib/x86_64-linux-gnu/libpthread.a /usr/include/pthread.h
using libpcre: /lib/x86_64-linux-gnu/libpcre.so /usr/include/pcre.h
using semaphore: /usr/include/semaphore.h
using libdl: /lib/x86_64-linux-gnu/libdl.a /usr/include/dlfcn.h
using libedit: /usr/include/editline/readline.h
using libpng: /lib/x86_64-linux-gnu/libpng.so /usr/include/png.h
using zlib: /lib/x86_64-linux-gnu/libz.so /usr/include/zlib.h
using mman: /usr/include/x86_64-linux-gnu/sys/mman.h
using libSDL2: /usr/include/SDL2/SDL.h
*** No SDL ttf support available.  BESM-6 video panel disabled.
***
*** Info *** Install the development components of libSDL2-ttf
*** Info *** packaged for your Linux operating system distribution:
*** Info ***        $ sudo apt-get install libsdl2-ttf-dev
using libpcap: /usr/include/pcap.h
using libvdeplug: /lib/x86_64-linux-gnu/libvdeplug.so /usr/include/libvdeplug.h
***
*** pdp11 Simulator being built with:
*** - compiler optimizations and no debugging support. GCC Version: 13.2.0.
*** - dynamic networking support using Linux provided libpcap components.
*** - Local LAN packet transports: PCAP VDE TAP NAT(SLiRP)
*** - video capabilities provided by libSDL2 (Simple Directmedia Layer).
*** - Per simulator tests will be run.
***
*** git commit id is aea2634940b4556f8ee746e5f20d4570e9ecfcb6.
*** git commit time is 2024-06-08T13:53:17-0700.
***
gcc -std=gnu99 -U__STRICT_ANSI__  -O2 -DNDEBUG=1 -finline-functions -fgcse-after-reload -fpredictive-commoning -fipa-cp-clone -fno-unsafe-loop-optimizations -fno-strict-overflow -DSIM_GIT_COMMIT_ID=aea2634940b4556f8ee746e5f20d4570e9ecfcb6 -DSIM_GIT_COMMIT_TIME=2024-06-08T13:53:17-0700  -DSIM_COMPILER="GCC Version: 13.2.0" -DSIM_BUILD_TOOL=simh-makefile -I . -Werror -D_GNU_SOURCE -DHAVE_PCRE_H -DHAVE_SEMAPHORE -DHAVE_SYS_IOCTL -DHAVE_LINUX_CDROM -DSIM_HAVE_DLOPEN=so -DHAVE_EDITLINE -DHAVE_UTIME -DHAVE_LIBPNG -DHAVE_ZLIB -DHAVE_GLOB -DHAVE_SHM_OPEN  ./PDP11/pdp11_fp.c ./PDP11/pdp11_cpu.c ./PDP11/pdp11_dz.c ./PDP11/pdp11_cis.c ./PDP11/pdp11_lp.c ./PDP11/pdp11_rk.c ./PDP11/pdp11_rl.c ./PDP11/pdp11_rp.c ./PDP11/pdp11_rx.c ./PDP11/pdp11_stddev.c ./PDP11/pdp11_sys.c ./PDP11/pdp11_tc.c ./PDP11/pdp11_tm.c ./PDP11/pdp11_ts.c ./PDP11/pdp11_io.c ./PDP11/pdp11_rq.c ./PDP11/pdp11_tq.c ./PDP11/pdp11_pclk.c ./PDP11/pdp11_ry.c ./PDP11/pdp11_pt.c ./PDP11/pdp11_hk.c ./PDP11/pdp11_xq.c ./PDP11/pdp11_xu.c ./PDP11/pdp11_vh.c ./PDP11/pdp11_rh.c ./PDP11/pdp11_tu.c ./PDP11/pdp11_cpumod.c ./PDP11/pdp11_cr.c ./PDP11/pdp11_rf.c ./PDP11/pdp11_dl.c ./PDP11/pdp11_ta.c ./PDP11/pdp11_rc.c ./PDP11/pdp11_kg.c ./PDP11/pdp11_ke.c ./PDP11/pdp11_dc.c ./PDP11/pdp11_dmc.c ./PDP11/pdp11_kmc.c ./PDP11/pdp11_dup.c ./PDP11/pdp11_rs.c ./PDP11/pdp11_vt.c ./PDP11/pdp11_td.c ./PDP11/pdp11_io_lib.c ./PDP11/pdp11_rom.c ./PDP11/pdp11_ch.c ./PDP11/pdp11_dh.c ./PDP11/pdp11_ng.c ./PDP11/pdp11_daz.c ./PDP11/pdp11_tv.c ./PDP11/pdp11_mb.c ./PDP11/pdp11_rr.c ./display/display.c ./display/sim_ws.c ./display/ng.c ./display/vt11.c ./scp.c ./sim_console.c ./sim_fio.c ./sim_timer.c ./sim_sock.c ./sim_tmxr.c ./sim_ether.c ./sim_tape.c ./sim_disk.c ./sim_serial.c ./sim_video.c ./sim_imd.c ./sim_card.c -DVM_PDP11 -I ./PDP11 -DHAVE_PCAP_NETWORK -I/usr/include/ -DBPF_CONST_STRING -DUSE_SHARED -DHAVE_VDE_NETWORK -DHAVE_TAP_NETWORK -Islirp -Islirp_glue -Islirp_glue/qemu -DHAVE_SLIRP_NETWORK -DUSE_SIMH_SLIRP_DEBUG slirp/*.c slirp_glue/*.c -DUSE_DISPLAY -DHAVE_LIBSDL -DUSE_SIM_VIDEO `sdl2-config --cflags` `sdl2-config --libs` -DUSE_READER_THREAD -DSIM_ASYNCH_IO -o BIN/pdp11 -lm -lrt -lpthread -lpcre -ldl -ledit -ltermcap -lpng -lz -lvdeplug -Wl,-R,/lib/x86_64-linux-gnu/ -L/lib/x86_64-linux-gnu/
BIN/pdp11 RegisterSanityCheck  </dev/null
 Running internal register sanity checks on PDP-11 simulator.
*** Good Registers in PDP-11 simulator.
mark@Ubuntu-24-04x64:~/open-simh$ BIN/pdp11
PDP-11 simulator Open SIMH V4.1-0 Current        git commit id: aea26349
sim> show version
PDP-11 simulator Open SIMH V4.1-0 Current
    Simulator Framework Capabilities:
        32b data
        32b addresses
        Threaded Ethernet Packet transports:PCAP:TAP:VDE:NAT:UDP
        Idle/Throttling support is available
        Virtual Hard Disk (VHD) support
        RAW disk and CD/DVD ROM support
        Asynchronous I/O support (Lock free asynchronous event queue)
        Asynchronous Clock support
        FrontPanel API Version 12
    Host Platform:
        Compiler: GCC 13.2.0
        Simulator Compiled as C arch: x64 (Release Build) on Jun 18 2024 at 03:01:22
        Build Tool: simh-makefile
        Memory Access: Little Endian
        Memory Pointer Size: 64 bits
        Large File (>2GB) support
        SDL Video support: SDL Version 2.30.0, PNG Version 1.6.43, zlib: 1.3
        PCRE RegEx (Version 8.39 2016-06-14) support for EXPECT commands
        OS clock resolution: 1ms
        Time taken by msleep(1): 1ms
        Ethernet packet info: libpcap version 1.10.4 (with TPACKET_V3)
        OS: Linux Ubuntu-24-04x64 6.8.0-35-generic #35-Ubuntu SMP PREEMPT_DYNAMIC Mon May 20 15:51:52 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
        Processor Name: Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
        tar tool: tar (GNU tar) 1.35
        git commit id: aea26349
        git commit time: 2024-06-08T13:53:17-0700
```

**Comment by folkertvanheusden** [comment]
I used the cmake build system, maybe that's it?

**Comment by folkertvanheusden** [comment]
```
folkert@oensoens ~/Projects/PDP-11/work/simh (master)$ git pull
Already up to date.
folkert@oensoens ~/Projects/PDP-11/work/simh (master)$ rm -rf build
folkert@oensoens ~/Projects/PDP-11/work/simh (master)$ mkdir build
folkert@oensoens ~/Projects/PDP-11/work/simh (master)$ cd build/
folkert@oensoens ~/Projects/PDP-11/work/simh/build (master)$ cmake ..
-- CMAKE_MODULE_PATH: /home/folkert/Projects/PDP-11/work/simh/cmake;/home/folkert/Projects/PDP-11/work/simh/cmake/installer-customizations
-- The C compiler identification is GNU 13.2.0
-- The CXX compiler identification is GNU 13.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- CMAKE_BUILD_TYPE defaulted to Release
-- Setting NO_DEP_BUILD to TRUE, will NOT BUILD missing dependencies
-- CMAKE_LIBRARY_ARCHITECTURE set to x86_64-linux-gnu
-- Link Time Optimization NOT ENABLED.
-- Replacing '-O3' with '-O2'
-- Adding GNU-specific optimizations to CMAKE_C_FLAGS_RELEASE
--     -finline-functions
--     -fgcse-after-reload
--     -fpredictive-commoning
--     -fipa-cp-clone
--     -fno-unsafe-loop-optimizations
--     -fno-strict-overflow
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Looking for semaphore.h
-- Looking for semaphore.h - found
-- Looking for sem_timedwait
-- Looking for sem_timedwait - found
-- Looking for sys/ioctl.h
-- Looking for sys/ioctl.h - found
-- Looking for linux/cdrom.h
-- Looking for linux/cdrom.h - found
-- Looking for utime.h
-- Looking for utime.h - found
-- Looking for glob.h
-- Looking for glob.h - found
-- Looking for sys/mman.h
-- Looking for sys/mman.h - found
-- Looking for shm_open
-- Looking for shm_open - found
-- Looking for dlfcn.h
-- Looking for dlfcn.h - found
-- Looking for dlopen
-- Looking for dlopen - found
-- Looking for linux/if_tun.h
-- Looking for linux/if_tun.h - found
-- Could NOT find PCRE (missing: PCRE_LIBRARY PCRE_INCLUDE_DIR) 
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.a (found version "1.3")  
-- Could NOT find PNG (missing: PNG_LIBRARY PNG_PNG_INCLUDE_DIR) 
-- Could NOT find Freetype (missing: FREETYPE_LIBRARY FREETYPE_INCLUDE_DIRS) 
-- Could NOT find SDL2 (missing: SDL2_DIR)
-- Could NOT find SDL2_ttf (missing: SDL2_ttf_DIR)
-- Found PkgConfig: /usr/bin/pkg-config (found version "1.8.1") 
-- REQUIRED (missing: VDEPLUG_LIBRARY VDEPLUG_INCLUDE_DIR) 
-- Found PCAP: /usr/include  
-- Checking for module 'libpcre'
--   Package 'libpcre', required by 'virtual:world', not found
-- Checking for module 'libpng16'
--   Package 'libpng16', required by 'virtual:world', not found
-- Checking for module 'sdl2'
--   Package 'sdl2', required by 'virtual:world', not found
-- Checking for module 'SDL2'
--   Package 'SDL2', required by 'virtual:world', not found
-- Checking for module 'SDL2_ttf'
--   Package 'SDL2_ttf', required by 'virtual:world', not found
-- Checking for module 'sdl2_ttf'
--   Package 'sdl2_ttf', required by 'virtual:world', not found
-- Checking for module 'vdeplug'
--   Package 'vdeplug', required by 'virtual:world', not found
-- pcap_compile requires BPF_CONST_STRING
-- Libraries and features:

    * Build with video/graphics support. TRUE
    * Build with networking support .... TRUE
    * Build internal ROMS .............. Yes
    * Thread support ................... Platform-detected threading support
    * zlib ............................. interface ZLIB
    * Perl-Compatible RegExps........... unknown
    * PNG, Freetype, SDL2, SDL2_ttf .... unknown
    * Network support .................. PCAP dynamic, TAP, NAT(SLiRP)
    * OS Feature definitions:
      .. HAVE_SEMAPHORE
      .. _GNU_SOURCE
      .. HAVE_SYS_IOCTL
      .. HAVE_LINUX_CDROM
      .. HAVE_UTIME
      .. HAVE_GLOB
      .. HAVE_SHM_OPEN
      .. SIM_HAVE_DLOPEN=so
    * OS Feature libraries:
      .. dl
      .. m
    * 'cppcheck' ....................... disabled.

-- Git command is /usr/bin/git
-- Adding simulators
-- BESM6: Fonts found
      .. /usr/share/fonts/truetype/dejavu/DejaVuSans.ttf
      .. /usr/share/fonts/truetype/freefont/FreeSans.ttf
-- BESM6: Using /usr/share/fonts/truetype/dejavu/DejaVuSans.ttf
-- No SIMH_PACKAGE_SUFFIX supplied, default is Linux.
-- CPack output file name: simh-4.1.0-Linux
-- Configuring done (2.7s)
-- Generating done (0.3s)
-- Build files have been written to: /home/folkert/Projects/PDP-11/work/simh/build
folkert@oensoens ~/Projects/PDP-11/work/simh/build (master)$ make -j32
[  0%] Building C object CMakeFiles/BuildROMs.dir/sim_BuildROMs.c.o
[  0%] Building C object slirp/CMakeFiles/slirp.dir/dnssearch.c.o
[  0%] Building C object slirp/CMakeFiles/slirp.dir/if.c.o
[  0%] Building C object slirp/CMakeFiles/slirp.dir/misc.c.o
[  0%] Building C object slirp/CMakeFiles/slirp.dir/bootp.c.o
[  0%] Building C object CMakeFiles/frontpaneltest.dir/sim_sock.c.o
[  0%] Building C object slirp/CMakeFiles/slirp.dir/ip_icmp.c.o
...
[  5%] Built target simhcore
[  5%] Building C object ALTAIR/CMakeFiles/altair.dir/altair_sio.c.o
[  5%] Building C object ALTAIR/CMakeFiles/altair.dir/altair_cpu.c.o
[  5%] Building C object ALTAIR/CMakeFiles/altair.dir/altair_dsk.c.o
/home/folkert/Projects/PDP-11/work/simh/ALTAIR/altair_dsk.c: In function ‘dsk12’:
/home/folkert/Projects/PDP-11/work/simh/ALTAIR/altair_dsk.c:313:18: warning: variable ‘rtn’ set but not used [-Wunused-but-set-variable]
  313 |     static int32 rtn, i;
      |                  ^~~
/home/folkert/Projects/PDP-11/work/simh/ALTAIR/altair_dsk.c: In function ‘writebuf’:
/home/folkert/Projects/PDP-11/work/simh/ALTAIR/altair_dsk.c:353:11: warning: variable ‘rtn’ set but not used [-Wunused-but-set-variable]
  353 |     int32 rtn, i;
      |           ^~~
[  6%] Building C object ALTAIR/CMakeFiles/altair.dir/altair_sys.c.o
/home/folkert/Projects/PDP-11/work/simh/ALTAIR/altair_sys.c: In function ‘fprint_sym’:
/home/folkert/Projects/PDP-11/work/simh/ALTAIR/altair_sys.c:186:7: warning: variable ‘cflag’ set but not used [-Wunused-but-set-variable]
  186 | int32 cflag, c1, c2, inst, adr;
      |       ^~~~~
/home/folkert/Projects/PDP-11/work/simh/ALTAIR/altair_sys.c: In function ‘parse_sym’:
/home/folkert/Projects/PDP-11/work/simh/ALTAIR/altair_sys.c:234:7: warning: variable ‘cflag’ set but not used [-Wunused-but-set-variable]
  234 | int32 cflag, i = 0, j, r;
      |       ^~~~~
[  6%] Linking C executable /home/folkert/Projects/PDP-11/work/simh/BIN/altair
[  6%] Built target altair
[  6%] Building C object CMakeFiles/simhcore_video.dir/display/sim_ws.c.o
/home/folkert/Projects/PDP-11/work/simh/display/sim_ws.c:80:5: error: unknown type name ‘Uint8’
   80 |     Uint8 *data;
      |     ^~~~~
/home/folkert/Projects/PDP-11/work/simh/display/sim_ws.c:81:5: error: unknown type name ‘Uint8’
   81 |     Uint8 *mask;
      |     ^~~~~
/home/folkert/Projects/PDP-11/work/simh/display/sim_ws.c: In function ‘key_to_ascii’:
/home/folkert/Projects/PDP-11/work/simh/display/sim_ws.c:156:43: warning: variable ‘k_win’ set but not used [-Wunused-but-set-variable]
  156 |     static t_bool k_ctrl, k_shift, k_alt, k_win;
      |                                           ^~~~~
/home/folkert/Projects/PDP-11/work/simh/display/sim_ws.c:156:36: warning: variable ‘k_alt’ set but not used [-Wunused-but-set-variable]
  156 |     static t_bool k_ctrl, k_shift, k_alt, k_win;
      |                                    ^~~~~
/home/folkert/Projects/PDP-11/work/simh/display/sim_ws.c: In function ‘ws_poll’:
/home/folkert/Projects/PDP-11/work/simh/display/sim_ws.c:228:91: warning: passing argument 4 of ‘vid_set_cursor’ from incompatible pointer type [-Wincompatible-pointer-types]
  228 |                 vid_set_cursor (1, cross_cursor->width, cross_cursor->height, cross_cursor->data, cross_cursor->mask, cross_cursor->hot_x, cross_cursor->hot_y);
      |                                                                               ~~~~~~~~~~~~^~~~~~
      |                                                                                           |
      |                                                                                           int *
In file included from /home/folkert/Projects/PDP-11/work/simh/display/sim_ws.c:41:
/home/folkert/Projects/PDP-11/work/simh/sim_video.h:208:76: note: expected ‘uint8 *’ {aka ‘unsigned char *’} but argument is of type ‘int *’
  208 | t_stat vid_set_cursor (t_bool visible, uint32 width, uint32 height, uint8 *data, uint8 *mask, uint32 hot_x, uint32 hot_y);
      |                                                                     ~~~~~~~^~~~
/home/folkert/Projects/PDP-11/work/simh/display/sim_ws.c:228:111: warning: passing argument 5 of ‘vid_set_cursor’ from incompatible pointer type [-Wincompatible-pointer-types]
  228 |                 vid_set_cursor (1, cross_cursor->width, cross_cursor->height, cross_cursor->data, cross_cursor->mask, cross_cursor->hot_x, cross_cursor->hot_y);
      |                                                                                                   ~~~~~~~~~~~~^~~~~~
      |                                                                                                               |
      |                                                                                                               int *
/home/folkert/Projects/PDP-11/work/simh/sim_video.h:208:89: note: expected ‘uint8 *’ {aka ‘unsigned char *’} but argument is of type ‘int *’
  208 | t_stat vid_set_cursor (t_bool visible, uint32 width, uint32 height, uint8 *data, uint8 *mask, uint32 hot_x, uint32 hot_y);
      |                                                                                  ~~~~~~~^~~~
/home/folkert/Projects/PDP-11/work/simh/display/sim_ws.c:233:91: warning: passing argument 4 of ‘vid_set_cursor’ from incompatible pointer type [-Wincompatible-pointer-types]
  233 |                 vid_set_cursor (1, arrow_cursor->width, arrow_cursor->height, arrow_cursor->data, arrow_cursor->mask, arrow_cursor->hot_x, arrow_cursor->hot_y);
      |                                                                               ~~~~~~~~~~~~^~~~~~
      |                                                                                           |
      |                                                                                           int *
/home/folkert/Projects/PDP-11/work/simh/sim_video.h:208:76: note: expected ‘uint8 *’ {aka ‘unsigned char *’} but argument is of type ‘int *’
  208 | t_stat vid_set_cursor (t_bool visible, uint32 width, uint32 height, uint8 *data, uint8 *mask, uint32 hot_x, uint32 hot_y);
      |                                                                     ~~~~~~~^~~~
/home/folkert/Projects/PDP-11/work/simh/display/sim_ws.c:233:111: warning: passing argument 5 of ‘vid_set_cursor’ from incompatible pointer type [-Wincompatible-pointer-types]
  233 |                 vid_set_cursor (1, arrow_cursor->width, arrow_cursor->height, arrow_cursor->data, arrow_cursor->mask, arrow_cursor->hot_x, arrow_cursor->hot_y);
      |                                                                                                   ~~~~~~~~~~~~^~~~~~
      |                                                                                                               |
      |                                                                                                               int *
/home/folkert/Projects/PDP-11/work/simh/sim_video.h:208:89: note: expected ‘uint8 *’ {aka ‘unsigned char *’} but argument is of type ‘int *’
  208 | t_stat vid_set_cursor (t_bool visible, uint32 width, uint32 height, uint8 *data, uint8 *mask, uint32 hot_x, uint32 hot_y);
      |                                                                                  ~~~~~~~^~~~
/home/folkert/Projects/PDP-11/work/simh/display/sim_ws.c: In function ‘ws_create_cursor’:
/home/folkert/Projects/PDP-11/work/simh/display/sim_ws.c:313:1: error: unknown type name ‘Uint8’; did you mean ‘uint8’?
  313 | Uint8 *data = NULL;
      | ^~~~~
      | uint8
/home/folkert/Projects/PDP-11/work/simh/display/sim_ws.c:314:1: error: unknown type name ‘Uint8’; did you mean ‘uint8’?
  314 | Uint8 *mask = NULL;
      | ^~~~~
      | uint8
/home/folkert/Projects/PDP-11/work/simh/display/sim_ws.c:328:9: error: ‘Uint8’ undeclared (first use in this function); did you mean ‘uint8’?
  328 | data = (Uint8 *)calloc (1, (width / 8) * height);
      |         ^~~~~
      |         uint8
/home/folkert/Projects/PDP-11/work/simh/display/sim_ws.c:328:9: note: each undeclared identifier is reported only once for each function it appears in
/home/folkert/Projects/PDP-11/work/simh/display/sim_ws.c:328:16: error: expected expression before ‘)’ token
  328 | data = (Uint8 *)calloc (1, (width / 8) * height);
      |                ^
/home/folkert/Projects/PDP-11/work/simh/display/sim_ws.c:329:16: error: expected expression before ‘)’ token
  329 | mask = (Uint8 *)calloc (1, (width / 8) * height);
      |                ^
/home/folkert/Projects/PDP-11/work/simh/display/sim_ws.c: In function ‘ws_init’:
/home/folkert/Projects/PDP-11/work/simh/display/sim_ws.c:400:83: warning: passing argument 4 of ‘vid_set_cursor’ from incompatible pointer type [-Wincompatible-pointer-types]
  400 |         vid_set_cursor (1, arrow_cursor->width, arrow_cursor->height, arrow_cursor->data, arrow_cursor->mask, arrow_cursor->hot_x, arrow_cursor->hot_y);
      |                                                                       ~~~~~~~~~~~~^~~~~~
      |                                                                                   |
      |                                                                                   int *
/home/folkert/Projects/PDP-11/work/simh/sim_video.h:208:76: note: expected ‘uint8 *’ {aka ‘unsigned char *’} but argument is of type ‘int *’
  208 | t_stat vid_set_cursor (t_bool visible, uint32 width, uint32 height, uint8 *data, uint8 *mask, uint32 hot_x, uint32 hot_y);
      |                                                                     ~~~~~~~^~~~
/home/folkert/Projects/PDP-11/work/simh/display/sim_ws.c:400:103: warning: passing argument 5 of ‘vid_set_cursor’ from incompatible pointer type [-Wincompatible-pointer-types]
  400 |         vid_set_cursor (1, arrow_cursor->width, arrow_cursor->height, arrow_cursor->data, arrow_cursor->mask, arrow_cursor->hot_x, arrow_cursor->hot_y);
      |                                                                                           ~~~~~~~~~~~~^~~~~~
      |                                                                                                       |
      |                                                                                                       int *
/home/folkert/Projects/PDP-11/work/simh/sim_video.h:208:89: note: expected ‘uint8 *’ {aka ‘unsigned char *’} but argument is of type ‘int *’
  208 | t_stat vid_set_cursor (t_bool visible, uint32 width, uint32 height, uint8 *data, uint8 *mask, uint32 hot_x, uint32 hot_y);
      |                                                                                  ~~~~~~~^~~~
make[2]: *** [CMakeFiles/simhcore_video.dir/build.make:286: CMakeFiles/simhcore_video.dir/display/sim_ws.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1859: CMakeFiles/simhcore_video.dir/all] Error 2
make: *** [Makefile:166: all] Error 2
```

**Comment by Rhialto** [comment]
There are some more occurrences of this strangely named `Uint8` type. Since it is the odd one out, I would rename all of them.

In fact, I would propose to go further and simply use C99 standard named `uint8_t` etc everywhere. Even MSVC supports these now. For the few cases in `sim_defs.h` where old compilers are detected, we can simply use the currently written types to define the standard names instead of the home-grown names.

For 64 bits there are even stranger names, starting with `t_` instead of ending with `_t`, with some convoluted conditions and definitions. I would, as a later step, propose to normalify those too. There is a good chance that some of the current definitions that intend to name a 64-bit type are not correct for some compiler(s).

**Comment by pkoning2** [comment]
Fixing other Uint instances would be welcome.  The bigger change you mention makes sense as well but seems like a larger and separate cleanup effort.

**Comment by Rhialto** [comment]
Certainly. I expect it will be a big merge request... but fortunately easy to verify.

**Comment by folkertvanheusden** [comment]
Shall I? Or is someone else already working on it?

**Comment by Rhialto** [comment]
Go ahead. Although I was just looking at `Uint8` and it seems it is defined in an SDL header: `<SDL2/SDL_stdinc.h>`. So actually the values that are directly passed to or obtained from SDL2 should be this type. That would need some careful examination since the compiler's normal type-checking doesn't help for this.

**Comment by rcornwell** [comment]
I have replaced uintx with uintx_t whereever I can in my emulators.

**Comment by markpizz** [comment]
> Go ahead. Although I was just looking at Uint8 and it seems it is defined in an SDL header: <SDL2/SDL_stdinc.h>. So actually the values that are directly passed to or obtained from SDL2 should be this type. That would need some careful examination since the compiler's normal type-checking doesn't help for this.

There are compilers which specifically check the named type and not the base type it may be equivalent to.  The original change to sim_ws.c was in fact interfacing with SDL.

No one  has looked at why the cmake build sees a problem while the makefile doesn't.

**Comment by pkoning2** [comment]
It's not up to compilers to futz with the type comparison rules.  But they are different for C and C++.  Perhaps some compilers are defaulting to C++ compilation even though SIMH is C, not C++.

**Comment by markpizz** [comment]
The real problem here is with something in the cmake's setup that somehow doesn't include the right definitions.

It was incredible that this PR was merged a mere 5 hours after it was created while some basic questions were still on the table.

To quote @pkoning2:
> It's not up to compilers to futz with the type comparison rules. But they are different for C and C++. Perhaps some compilers are defaulting to C++ compilation even though SIMH is C, not C++.

Therefore the right fix is not to change the source code, but the cmake build system so it doesn't do this!  Something about his build environment might have been a factor here since it doesn't happen with the CI builds and on various other platforms.

**Pull request merged**
