### PR TITLE
Regular updates to B5500, I7000, PDP10

### PR DESCRIPTION
**Pull request by rcornwell**

### CODE REVIEW

**Comment by rcornwell** [comment]
It has been that way for years now. Also I believe I had to make some changes to it.

**Comment by pkoning2** [comment]
pdp11_ddcmp.h is newly added by this PR, and it's identical to the original.  So I agree with Mark: please use the original directly.  If at some point it has to diverge, then that could either be done with conditional compiles (as is done for some other files) or by making a copy then.

**Comment by rcornwell** [comment]
Done.

**Comment by markpizz** [comment]
1>..\PDP10\kx10_tym.c(549) : warning C4244: '=' : conversion from 'uint64' to 'int', possible loss of data

1>..\PDP10\ka10_dd.c(389) : error C2220: warning treated as error - no 'object' file generated
1>..\PDP10\ka10_dd.c(389) : warning C4101: 'j' : unreferenced local variable
1>..\PDP10\ka10_dd.c(519) : warning C4244: '=' : conversion from 'uint64' to 'int32', possible loss of data
1>..\PDP10\ka10_dd.c(544) : warning C4018: '>=' : signed/unsigned mismatch
1>..\PDP10\ka10_dd.c(657) : warning C4244: '=' : conversion from 't_value' to 'int', possible loss of data
1>..\PDP10\ka10_dd.c(729) : warning C4244: '=' : conversion from 'uint64' to 'uint32', possible loss of data

kx10_cpu.c has tabs rather than tabs expanded to spaces as is the simh project standard

ka10_dd_font.h and kx10_ddc.c have LF line endings instead of the simh project standard of CRLF

**Comment by rcornwell** [comment]
These two files were done by @larsbrinkhoff He needs to fix them.
As to kx10_cpu.c I will verify there are no tabs.

**Pull request merged**
