### PR TITLE
AltairZ80: Correct spelling, formatting and years

### PR DESCRIPTION
**Pull request by psco**

### CODE REVIEW

**Comment by pkoning2** [comment]
I see a bunch of files with just a copyright date change.  Did you actually change those in earlier PRs?  If not, please don't do that.  I know some projects change the copyright year on every file every year.  In my view this is incorrect and a misunderstanding of how copyright works.  If you change a file,  by all means adjust the copyright date accordingly, but not if the file hasn't changed.

**Comment by psco** [comment]
I'd like to update the copyright dates about every 10 years. I think this should be ok.

**Comment by pkoning2** [comment]
It doesn't make a whole lot of practical difference because of the duration of copyright, but that really isn't right.  Copyright attaches to a "work", meaning something you created, or revised.  So a change comes with a copyright date matching that change.  But the elapsing of time doesn't change the effective date of the copyright.  In other words, no matter what the header may say, legally (as I, not a lawyer, understand it) the actual copyright dates are the creation and revision dates of the work in question.

**Comment by psco** [comment]
If I understand you right you are opposed to just updating the copyright year if there is no change otherwise. If this is the case I'll make sure that all files where I just updated the year will also have some other change. Would this be acceptable?

**Comment by markpizz** [comment]
As I understand the current copyright concepts, a copyright exists explicitly with the authorship of a work without any regard to explicit declaration/language claiming copyright.  Authorship, by itself, is all that is needed.

**Comment by pkoning2** [comment]
> As I understand the current copyright concepts, a copyright exists explicitly with the authorship of a work without any regard to explicit declaration/language claiming copyright. Authorship, by itself, is all that is needed.

Yes, that's right.  So the copyright header is redundant, but serves a useful purpose in making things explicit.

**Pull request merged**
